#!/bin/env python3

import click
from pathlib import Path

@click.command()
@click.option('--timeout', '-t', type=int, default=1500,
              help='Timeout to be used by the daphne controllers in milliseconds')
@click.option('--name', '-n', type=str, default="",
              help='Name assigned to the object. If empty its name is derived from the json file name')
@click.argument('oksfile')
@click.argument('jsonfile')
def cli(oksfile, jsonfile, name, timeout):
  """Script to set the SSP for a particular calibration phase space"""
  if not name:
     name = Path(jsonfile).stem
     
  daphne.add_daphne_conf(oksfile, name, jsonfile, timeout)

if __name__ == '__main__':
  cli()