#!/bin/env python3

import click
import conffwk
import confmodel
import appmodel

@click.command()
@click.option('--object-name', '-n', type=str, default="np02-ssp-on",
              help='Name assigned to the object')
@click.option('--number-channels', type=int, default=None)
@click.option('--channel-mask', type=int, default=None)
@click.option('--pulse-mode', type=str, default=None)
@click.option('--burst-count', type=int, default=None)
@click.option('--double-pulse-delay-ticks', type=int, default=None)
@click.option('--pulse1-width-ticks', type=int, default=None)
@click.option('--pulse2-width-ticks', type=int, default=None)
@click.option('--pulse-bias-percent-270nm', type=int, default=None)
@click.option('--pulse-bias-percent-367nm', type=int, default=None)
@click.argument('oksfile')
def cli(oksfile, object_name,
        number_channels, channel_mask, pulse_mode, burst_count, double_pulse_delay_ticks,
        pulse1_width_ticks, pulse2_width_ticks, pulse_bias_percent_270nm, pulse_bias_percent_367nm):
  """Script to set the SSP for a particular calibration phase space"""

  db = conffwk.Configuration("oksconflibs:" + oksfile)
  dal=db.get_dal(class_name="SSPLEDCalibModule", uid=object_name)

  if number_channels :
    dal.number_channels = number_channels
  if channel_mask :
    dal.channel_mask = channel_mask
  if pulse_mode :
    dal.pulse_mode = pulse_mode
  if burst_count :
    dal.burst_count = burst_count
  if double_pulse_delay_ticks :
    dal.double_pulse_delay_ticks = double_pulse_delay_ticks
  if pulse1_width_ticks :
    dal.pulse1_width_ticks = pulse1_width_ticks
  if pulse2_width_ticks :
    dal.pulse2_width_ticks = pulse2_width_ticks
  if pulse_bias_percent_270nm :
    dal.pulse_bias_percent_270nm = pulse_bias_percent_270nm 
  if pulse_bias_percent_367nm :
    dal.pulse_bias_percent_367nm = pulse_bias_percent_367nm 
    
  db.update_dal(dal)
  db.commit()
  
if __name__ == '__main__':
  cli()
